### ISSUE TITLE
Has this really finished?

### ISSUE THREAD

**Issue by g0g5** [Hou-Rui/pybasic#1]
Well, I wan't to have a simple BASIC code runner in my project. 
Is the code provided here really usable/ ready-to-use? Or just a placeholder and no more updates?
If this can't be used, anything pratical I can choose instead?

**Comment by Hou-Rui** [comment]
Hi, I'm quite surprised someone express interest to this project...

The code should work for the examples, but this is a *toy* project I did when I was just a kid, back when I knew little about compiler design. Now I'm an actual CS student and have much more coding things to do, so I probably will not give more updates to this project (nor like it was designed for practical use anyway).

AFAIK there's no mature lightweight Python implementation for simple BASIC programs. Since Python itself is a scripting language, it is easy to use Python to extend existing Python application (such as Sublime Text extensions), providing interface modules exported by the application, without the need of another scripting language such as JavaScript or BASIC.

If you want a practical BASIC *compiler* for desktop, [FreeBASIC](https://github.com/freebasic/fbc) might be a good choice. Although not related to Python, it's mature, open-source, and multi-platform. But it is by no means lightweight and produces native code, and should be seen as a Visual Basic alternative.

If you only need a scripting engine in your project, there are many better choices other than BASIC, such as Lua, JavaScript, Python, Guile, etc., which are better and more widely supported on any platform.

Hope these suggestions can you.

**Comment by g0g5** [comment]
Thanks for your suggestions.
